set encoding=utf-8 fileencodings=

set number
set cc=80
set tabstop=4
set shiftwidth =4
set softtabstop=4
set expandtab
autocmd Filetype make setlocal noexpandtab

set list listchars=tab:»\ ,trail:·
filetype plugin indent on
set autoindent
set smartindent
syntax on
