# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")];

	boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ata_piix" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
	boot.initrd.kernelModules = [ "dm-snapshot" "dm-mod" "dm-cache" "dm-cache-smq" "dm-thin-pool" "dm-raid" "raid1" "dm-crypt" "dm-raid1" ];
	boot.kernelModules = [ "kvm-intel" "vfio_pci" "vfio" "vfio_iommu_type1" "vfio_virqfd" ];
	boot.extraModulePackages = [ ];
	boot.kernelParams = [ "intel_iommu=on" "iommu=pt" "vfio-pci.ids=10de:1c81,10de:0fb9" ];
	boot.extraModprobeConfig = ''
		options vfio-pci ids=10de:1c81,10de:0fb9
		options kvm_intel nested=1
		'';
	boot.kernel.sysctl = {
		"net.ipv4.ip_forward" = 1;
	};

	services.lvm.boot.thin.enable = true;

	boot.initrd.luks.devices = {
		cryptlvm = {
			device = "/dev/vl_data/vl_raid";
			preLVM = false;
		};
	};

	fileSystems."/" =
	{ device = "/dev/disk/by-uuid/26b71779-23c3-443b-b905-3ccd872b889b";
		fsType = "ext4";
	};

	fileSystems."/boot" =
	{ device = "/dev/disk/by-uuid/2A25-FAE6";
		fsType = "vfat";
	};

	swapDevices = [ ];

	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
