export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="clean"

plugins=(git history vi-mode zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

# User configuration

export TERM=xterm-256color

alias vi=nvim
alias vim=nvim
alias k=kubectl

export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
gpg-connect-agent updatestartuptty /bye > /dev/null

alias perso="~/Work/Perso/"
